import { pgTable, text, uuid, numeric, timestamp, jsonb, boolean, integer } from "drizzle-orm/pg-core";

export const dealsTable = pgTable("deals", {
  id: uuid("id").primaryKey().defaultRandom(),
  deal_number: text("deal_number").notNull(),
  quote_id: uuid("quote_id"),
  customer_id: uuid("customer_id"),
  lead_id: uuid("lead_id"),
  salesperson_id: uuid("salesperson_id"),
  salesperson_user_id: uuid("salesperson_user_id"),
  payment_status: text("payment_status"),
  execution_status: text("execution_status").notNull().default("פתוחה"),
  purchase_date: text("purchase_date"),
  next_payment_date: text("next_payment_date"),
  total_amount: numeric("total_amount"),
  total_amount_including_vat: numeric("total_amount_including_vat"),
  paid_amount: numeric("paid_amount"),
  amount_paid_including_vat: numeric("amount_paid_including_vat"),
  remaining_amount: numeric("remaining_amount"),
  payment_type: text("payment_type"),
  installments_count: integer("installments_count"),
  invoice_name: text("invoice_name"),
  invoice_id_number: text("invoice_id_number"),
  invoice_email: text("invoice_email"),
  coordination_tasks_requested: boolean("coordination_tasks_requested").default(false),
  quote_link: text("quote_link"),
  what_is_included: text("what_is_included"),
  special_notes: text("special_notes"),
  studio_hours_remaining: numeric("studio_hours_remaining"),
  editing_tasks_remaining: numeric("editing_tasks_remaining"),
  monday_board_id: text("monday_board_id"),
  monday_item_id: text("monday_item_id"),
  monday_group_id: text("monday_group_id"),
  monday_raw_data: jsonb("monday_raw_data"),
  source_quote_version_id: uuid("source_quote_version_id"),
  party_snapshot: jsonb("party_snapshot"),
  items_snapshot: jsonb("items_snapshot"),
  totals_snapshot: jsonb("totals_snapshot"),
  terms_snapshot: jsonb("terms_snapshot"),
  notes_snapshot: jsonb("notes_snapshot"),
  snapshot_locked_at: timestamp("snapshot_locked_at", { withTimezone: true }),
  created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  deleted_at: timestamp("deleted_at", { withTimezone: true }),
});

export type Deal = typeof dealsTable.$inferSelect;
